CREATE TABLE Products(
PRODUCT_ID INT PRIMARY KEY IDENTITY(1,1),
PRODUCT_NAME NVARCHAR(100) NOT NULL,
PRICE DECIMAL(10,2) CHECK (PRICE>0),
STOCK INT DEFAULT 0 CHECK (STOCK>=0),
DESCRIPTION NVARCHAR(MAX) NULL
);

CREATE TABLE ORDERS (
ORDERID INT PRIMARY KEY IDENTITY(1,1),
PRODUCT_ID INT NOT NULL FOREIGN KEY REFERENCES Products(PRODUCT_ID) ON DELETE CASCADE,
QUANTITY INT NOT NULL CHECK(QUANTITY>0),
ORDERDATE DATETIME DEFAULT GETDATE(), 
);

INSERT INTO Products (PRODUCT_NAME, PRICE, STOCK, DESCRIPTION)
VALUES ('LAPTOP', 80000, 30, 'High performance laptops'),('mouse',2000,40,'ergonomic design');

--DROP TABLE ORDERS;

